name: Repo Traffic Backup

on:
  schedule:
    - cron: "0 23 * * *"   # once a day, 23:00 UTC
  workflow_dispatch:        # lets you run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          ghtoken: ${{ secrets.TRAFFIC_TOKEN }}
